@startuml
left to right direction

RaptorsApp as RaptorsApp
User -- (Visualize Bariers)

(Visualize Bariers) .> (Generate Barriers) :includes
RaptorsApp -- (Generate Barriers)
RaptorsApp -- (Load Map)
(Load Map) -- RaptorsDatabase
@enduml